import { TProductCollectionFaker } from '@/types/faker.type';

export const PRODUCT_COLLECTION_FAKER: TProductCollectionFaker[] = [
  {
    status: true,
    collection_name: 'Drill Tools',
    category: 'Precision Cutting Tolls',
    product_list: [
      'Subland Drill 90º',
      'Subland Drill 90º',
      'Subland Drill 90º',
    ],
    store_id: 'Example Store 1',
    collection_price: 'SAR440',
    collection_discount_price: 'SAR400',
  },
  {
    status: true,
    collection_name: 'Drill Tools',
    category: 'Precision Cutting Tolls',
    product_list: [
      'Subland Drill 90º',
      'Subland Drill 90º',
      'Subland Drill 90º',
    ],
    store_id: 'Example Store 1',
    collection_price: 'SAR440',
    collection_discount_price: '-',
  },
  {
    status: false,
    collection_name: 'Motor',
    category: 'Motor System',
    product_list: ['Slotless Motor', 'AC Motor'],
    store_id: 'Example Store 1',
    collection_price: 'SAR440',
    collection_discount_price: '-',
  },
  {
    status: false,
    collection_name: 'Motor',
    category: 'Motor System',
    product_list: ['Slotless Motor', 'AC Motor'],
    store_id: 'Example Store 1',
    collection_price: 'SAR440',
    collection_discount_price: '-',
  },
];

export const SALE_ITEM_FAKER = [
  {
    status: true,
    product_name: 'Subland Drill 90 º',
    thumbnail: 'pd-1.jpg',
    stock: 5,
    min_price: 'SAR 240',
    max_price: 'SAR 240',
    disc_price: 'none',
    min_order: 1,
    max_order: 4,
    store_id: 'Example Store 1',
    sku: '837619365',
    brand: 'ProCut Engineering',
    category: 'Precision Cutting Tools',
    mpn: '978020137962',
  },
  {
    status: false,
    product_name: 'Slotless Motor',
    thumbnail: 'list-3.jpg',
    stock: 20,
    min_price: 'SAR 240',
    max_price: 'SAR 244',
    disc_price: 'SAR 200',
    min_order: 1,
    max_order: 4,
    store_id: 'Example Store 1',
    sku: '837254859',
    brand: 'UltraMotion Tech',
    category: 'Motor System',
    mpn: '978020137962',
  },
  {
    status: false,
    product_name: 'Slotless Motor',
    thumbnail: 'product-4.jpg',
    stock: 20,
    min_price: 'SAR 240',
    max_price: 'SAR 244',
    disc_price: 'SAR 200',
    min_order: 1,
    max_order: 4,
    store_id: 'Example Store 1',
    sku: '837254859',
    brand: 'CoolBreeze Motors',
    category: 'Motor System',
    mpn: '978020137962',
  },
];
